<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQaV1Kff\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQaV1Kff/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQaV1Kff.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQaV1Kff\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerQaV1Kff\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'QaV1Kff',
    'container.build_id' => '58e0b843',
    'container.build_time' => 1568969104,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQaV1Kff');
